language:
 - python
python:
 - "3.6"
install:
 - pip install -r requirements.txt
 - pip install coveralls
script:
 - source scripts/env.sh
 - ./scripts/create_test_env.sh
 - cd ${sitename} && coverage run --source='./ilmo_app' manage.py test ilmo_app && cd ..
 - ./scripts/run_tests.sh --teardown
after_success:
- coveralls
